USE taskdb;

CREATE TABLE scheduled_tasks (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL,
    execute_at DATETIME(3) NOT NULL,
    payload JSON NOT NULL,
    claim_by VARCHAR(64),
    claim_at DATETIME(3),
    status ENUM('PENDING','PROCESSING','TRIGGERED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_task_id (task_id)
);

